
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css"
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { Providers } from "./providers";
import NavbarController from "@/components/NavBarController";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { getUser } = getKindeServerSession();
  const user =await getUser();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <NavbarController user={user}></NavbarController>
          {children}
          <footer>Footer</footer>
        </Providers>
      </body>
    </html>
  );
}